# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newp_app1', '0002_auto_20171109_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
