# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('author', models.CharField(max_length=128)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('desc', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
