# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide_model',
            name='date_added',
        ),
    ]
